movie_se_de:
  outputs:
    dev:
      dataset: movie_data_mar25_sumant
      job_execution_timeout_seconds: 300
      job_retries: 2
      keyfile: ./creds.json
      location: us-central1
      method: service-account
      priority: interactive
      project: ee-india-se-data
      threads: 1
      type: bigquery
  target: dev
