name: Deploy cloudfunction

env:
  project_id: ee-india-se-data
  REGION: us-east1
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_DEFAULT_CREDENTIAL }}


on: 
  push:
    branches: 
      - main
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.8
      - name: Terraform fmt
        id: fmt
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: Init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run:  terraform init
      - name: Terraform Plan
        id: plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: terraform plan -no-color