name: Deploy cloudfunction

env:
  project_id: ee-india-se-data
  SERVICE: se-data-india-service-account
  REGION: us-east1

on: 
  push:
    branches: 
      - main
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Google Cloud credentials
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.8
      - name: Terraform fmt
        id: fmt
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run:  terraform init -upgrade
      - name: Terraform Plan
        id: plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: terraform plan -no-color
      - name: Terraform Apply
        id: apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: terraform apply -auto-approve
        